/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Patient;
import java.awt.Dimension;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
/**
 *
 * @author shrajnashetty
 * 
 */
public class ViewPanel extends javax.swing.JPanel {
    private Patient patient;

    public ViewPanel(Patient patient) {
        initComponents();
        this.patient = patient;
        populateData();
    }

    ViewPanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderButtonGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AgeComboBox = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        FemaleRadioButton = new javax.swing.JRadioButton();
        MaleRadioButton = new javax.swing.JRadioButton();
        PreferNotRadioButton = new javax.swing.JRadioButton();
        AgeTextField = new javax.swing.JTextField();
        MessageLabel = new javax.swing.JLabel();
        MessageScrollPanel = new javax.swing.JScrollPane();
        MessageTextArea = new javax.swing.JTextArea();
        TypeLabel = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        DateOfBirthLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        UploadPhoto = new javax.swing.JLabel();
        previewImage = new javax.swing.JLabel();

        MainPanel.setBackground(new java.awt.Color(204, 204, 204));

        TitleLabel.setFont(new java.awt.Font("AppleMyungjo", 3, 24)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("VIEW INFO");

        FirstNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        FirstNameLabel.setText("First Name :");

        LastNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LastNameLabel.setText("Last Name :");

        AgeComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        AgeComboBox.setText("Age :");

        EmailLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        EmailLabel.setText("Email :");

        GenderLabel.setText("Gender :");

        FirstNameTextField.setToolTipText("");

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        GenderButtonGroup.add(FemaleRadioButton);
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.setActionCommand("FEMALE");

        GenderButtonGroup.add(MaleRadioButton);
        MaleRadioButton.setText("Male");
        MaleRadioButton.setActionCommand("MALE");

        GenderButtonGroup.add(PreferNotRadioButton);
        PreferNotRadioButton.setText("Prefer not to say");
        PreferNotRadioButton.setActionCommand("NOT SPECIFIED");

        MessageLabel.setText("Message :");

        MessageTextArea.setColumns(20);
        MessageTextArea.setRows(5);
        MessageScrollPanel.setViewportView(MessageTextArea);

        TypeLabel.setText("Type :");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pediatric", "Chronic", "Acute" }));
        TypeComboBox.setSelectedIndex(-1);
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });

        DateOfBirthLabel.setText("Date Of Birth :");

        UploadPhoto.setText("Uploaded Image :");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MessageLabel)
                            .addComponent(FirstNameLabel)
                            .addComponent(LastNameLabel)
                            .addComponent(AgeComboBox)
                            .addComponent(EmailLabel)
                            .addComponent(GenderLabel)
                            .addComponent(TypeLabel)
                            .addComponent(DateOfBirthLabel)
                            .addComponent(UploadPhoto))
                        .addGap(158, 158, 158)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MessageScrollPanel)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(MaleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(FemaleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(PreferNotRadioButton))
                            .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailTextField)
                            .addComponent(LastNameTextField)
                            .addComponent(FirstNameTextField)
                            .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previewImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeComboBox)
                    .addComponent(AgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(MaleRadioButton)
                    .addComponent(FemaleRadioButton)
                    .addComponent(PreferNotRadioButton))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLabel)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(DateOfBirthLabel))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(MessageScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(MessageLabel)))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UploadPhoto)
                    .addComponent(previewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeComboBox;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JScrollPane MessageScrollPanel;
    private javax.swing.JTextArea MessageTextArea;
    private javax.swing.JRadioButton PreferNotRadioButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel UploadPhoto;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel previewImage;
    // End of variables declaration//GEN-END:variables

void populateData() {
    FirstNameTextField.setText(patient.getfirstName());
    LastNameTextField.setText(patient.getlastName());
    AgeTextField.setText(patient.getage());
    EmailTextField.setText(patient.getemail());
    String gender = patient.getgender();
    if (gender.equals("MALE")) {
        MaleRadioButton.setSelected(true);
    } else if (gender.equals("FEMALE")) {
        FemaleRadioButton.setSelected(true);
    } else {
        PreferNotRadioButton.setSelected(true);
    }
    MessageTextArea.setText(patient.getmessage());
    String type = patient.gettype();
    TypeComboBox.setSelectedItem(type);
    Date dateOfBirth = patient.getDateOfBirth();
    if (dateOfBirth != null) {
        jDateChooser1.setDate(dateOfBirth);
    }

    String imagePath = patient.getImagePath();
    if (imagePath != null) {
        ImageIcon imageIcon = new ImageIcon(imagePath);

        int labelWidth = 81;
        int labelHeight = 89;
        previewImage.setPreferredSize(new Dimension(labelWidth, labelHeight));

        if (labelWidth > 0 && labelHeight > 0) {
            Image image = imageIcon.getImage();
            Image scaledImage = image.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(scaledImage);
        }
        previewImage.setIcon(imageIcon);
    }
}
}
    

